In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2, random_state=25)


In [6]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [8]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 494ms/step - loss: 0.7113 - accuracy: 0.5000
Epoch 2/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7110 - accuracy: 0.5000
Epoch 3/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7106 - accuracy: 0.5000
Epoch 4/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7102 - accuracy: 0.5000
Epoch 5/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7098 - accuracy: 0.5000
Epoch 6/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7094 - accuracy: 0.5000
Epoch 7/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7091 - accuracy: 0.5000
Epoch 8/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7087 - accuracy: 0.5000
Epoch 9/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7083 - accuracy: 0.5000
Epoch 10/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7079 - accuracy: 0.5000
Epoch 11/500
1/1 [========

In [9]:
model.evaluate(X_test_scaled,y_test)

1/1 [==============================] - 0s 165ms/step - loss: 0.6210 - accuracy: 0.6667


[0.621041476726532, 0.6666666865348816]

In [10]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 73ms/step


array([[0.66075516],
       [0.6084721 ],
       [0.45149705],
       [0.6268543 ],
       [0.66423655],
       [0.68474233]], dtype=float32)

In [11]:
coef, intercept = model.get_weights()
coef,intercept

(array([[0.7785071 ],
        [0.69779867]], dtype=float32),
 array([-0.39703575], dtype=float32))

This means w1=0.7785071, w2=0.69779867, bias =-0.39703575


In [12]:
def sigmoid(x):
        import math
        return 1 / (1 + math.exp(-x))
sigmoid(18)

0.9999999847700205

In [13]:
def prediction_function(age, affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

prediction_function(.47, 1)

0.6607551573836065

In [14]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])